generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Bookings
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          bookings
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
         published_named:
            label: Published
      list:    
         display: [name,published_named]
      filter:  
         display: [name,published]
      form:    
        display: 
          "Name" : [name]
          "Published" : [published]
      edit:    ~
      new:     ~
