SubmissionsImported:
  connection: doctrine
  tableName: submissions_imported
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fname:
      type: string(100)
      fixed: true
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    lname:
      type: string(100)
      fixed: true
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    age:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    height:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    gender:
      type: string(5)
      fixed: true
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    weight:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    modeling:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    acting:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    theater:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    address:
      type: string(150)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    city:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    state:
      type: string(2)
      fixed: true
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    zipcode:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    phone:
      type: string(10)
      fixed: true
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    cellphone:
      type: string(10)
      fixed: true
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(150)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    comments:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
