States:
  connection: doctrine
  tableName: states
  actAs: [Timestampable,SoftDelete]
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    deleted_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    state:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    abbreviation:
      type: string(20)
      fixed: true
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Submissions:
      local: id
      foreign: state
      type: many